#create Pod object with meatadata (name and description) & ubuntu containers with environment variables
kind: Pod
apiVersion: v1
metadata:
  name: testpod2
  annotations:
    description: my testpod
spec:
  containers:
    - name: c02
      image: ubuntu
      command: ["/bin/bash" ,"-c", "while true;do echo 'hi aravivo'; sleep 2; done"]
      env:
        - name: myname
          value: aravivo-se
    - name: c03
      image: centos
      command: ["/bin/bash" ,"-c", "while true;do echo 'hi raj'; sleep 2; done"]