---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mydeployent
  template:
    metadata:
      labels:
        name: mydeployent
    spec:
      containers:
        - name: c01
          image: httpd
          ports:
            - containerPort: 81

---
kind: Service
apiVersion: v1
metadata:
  name: demo-service
spec:
  ports:
    - port: 8081 # service port given by user (0 - 65535)
      targetPort: 81 #container port
  selector:
    name: mydeployent
  #type: ClusterIP
  type: NodePort
