kind: Pod
apiVersion: v1
metadata:
  name: readinesspod1

spec:
  containers:
    - name: c1
      image: ubuntu/apache2
      ports:
        - containerPort: 80
      readinessProbe:
        initialDelaySeconds: 10
        httpGet:
          path: /
          port: 80