kind: Pod
apiVersion: v1
metadata:
  name: my-env-secret
spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["/bin/bash","-c","while true; do echo 'Hi'; sleep 10; done"]
      env:
        - name: MYNAME
          valueFrom:
            secretKeyRef:
              name: myyamlsecret
              key: myname #value from secretobject data section