kind: Pod
apiVersion: v1
metadata:
  name: envsecret
spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["/bin/bash","-c","while true; do echo 'Hi..!'; sleep 10; done"]
      env:
        - name: ENVUSER
          valueFrom:
            secretKeyRef:
              name: mytestsecret
              key: username.txt
        - name: ENVPASSWORD
          valueFrom:
            secretKeyRef:
              name: mytestsecret
              key: password.txt
