kind: Pod
apiVersion: v1
metadata:
  name: vol-secret
spec:
  containers:
    - name: c1
      image: centos
      command: ["/bin/bash", "-c","while true; do echo 'Hi raj..!!'; sleep 10; done"]
      volumeMounts:
        - name: testsecret
          mountPath: "/tmp/secretDir"
  volumes:
    - name: testsecret
      secret:
        secretName: mytestsecret